ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),

    path('inicio/', include('ProyectoWebApp.urls')),

    path('servicios/', include('servicios.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('tienda/', include('tienda.urls')),

    path('carro/', include('carro.urls')),

    path('login/', include('login.urls')),

    path('comentarios/', include('misComentarios.urls')),

    


    

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoWeb/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.blog, name="Blog"), 
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria")

]

ProyectoWeb/misComentarios/urls.py
from django.urls import path

from . import views

app_name='misComentarios'

urlpatterns = [

    path('', views.comentarios, name="Coment"), 
    path('eliminar/<int:comentario_id>/', views.eliminar_comentario, name='eliminar'),
    
    

]

ProyectoWeb/misComentarios/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Comentarios(models.Model):
    
    mensaje=models.TextField()
    autor=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='miComentario'
        verbose_name_plural='misComentarios'

ProyectoWeb/misComentarios/forms.py
from django import forms



class FormularioComentarios(forms.Form):
    mensaje = forms.CharField(label='Comentario', widget=forms.Textarea)

ProyectoWeb/misComentarios/views.py
from django.shortcuts import render, redirect

from .models import Comentarios
from .forms import FormularioComentarios
from django.contrib.auth.models import User






def comentarios(request):
    comentarios=Comentarios.objects.all()
    
    if request.method=='POST':

        formulario_comentarios=FormularioComentarios(request.POST)

        if formulario_comentarios.is_valid():
            
            comentario= Comentarios()#el modelo

            comentario.mensaje=formulario_comentarios.cleaned_data['mensaje']
            comentario.autor=request.user.username
            comentario.save()
            
            
            
            return redirect('/comentarios')
            
        
    else:
        formulario_comentarios = FormularioComentarios()
        


    return render(request, 'comentarios/comentarios.html', {"comentarios" : comentarios, "form" : formulario_comentarios})

def eliminar_comentario(request, comentario_id):

    comentario=Comentarios.objects.get(id=comentario_id)

    comentario.delete()

    return redirect('/comentarios')

ProyectoWeb/misComentarios/templates/comentarios/comentarios.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}

    {% if user.email != null %}

    

    <div class="contenedorFormulario">

        
    
        <form action="" method="POST" style="text-align: center;">
            {% csrf_token %}
            <table style="color: blanchedalmond; margin: 20px auto">{{form.as_table}}</table>
            <input type="submit" value="Enviar" >
    
        </form>
    
    </div>



    {% endif %}

    {% for comentario in comentarios %} 

    <div class="contenedorFormulario" style="color:white">
    <h1>{{comentario.mensaje}}</h1>
    <h2>{{comentario.autor}}</h2>
    <h2>{{comentario.created}}</h2>
    
    
    {% if comentario.autor == user.username %}

    <a href='{% url "misComentarios:eliminar" comentario.id %}' class='btn btn-success'>Eliminar</a>

    
    

    {% endif %}
</div>

    {% endfor %}

    
    
                

{% endblock %}