ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),

    path('inicio/', include('ProyectoWebApp.urls')),

    path('servicios/', include('servicios.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('tienda/', include('tienda.urls')),

    path('carro/', include('carro.urls')),

    path('login/', include('login.urls')),

    path('comentarios/', include('misComentarios.urls')),

    


    

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoWeb/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.blog, name="Blog"), 
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria")

]

ProyectoWeb/carro/urls.py
from django.urls import path

from . import views

app_name='carro'



urlpatterns = [
    
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('comprar/', views.comprar_producto, name='comprar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
    


]

ProyectoWeb/tienda/urls.py
from django.urls import path

from . import views



urlpatterns = [
    
    path('', views.tienda, name="Tienda"),


]

ProyectoWeb/carro/models.py
from django.db import models

# Create your models here.

ProyectoWeb/tienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='categoriaProd'  
        verbose_name_plural='categoriasProd'

    def __str__(self):
        return self.nombre



class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='tienda', null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='producto'  
        verbose_name_plural='productos'

    def __str__(self):
        return self.nombre

ProyectoWeb/carro/views.py
from django.shortcuts import render

from .carro import Carro

from tienda.models import Producto

from django.shortcuts import redirect

from django.core.mail import EmailMessage

# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)#creo objeto tipo carro

    producto=Producto.objects.get(id=producto_id)#obtengo el producto

    carro.agregar(producto=producto)

    return redirect('Tienda') #para refrescar la pagina

def eliminar_producto(request, producto_id):

    carro=Carro(request)#creo objeto tipo carro

    producto=Producto.objects.get(id=producto_id)#obtengo el producto

    carro.eliminar(producto=producto)

    return redirect('Tienda') #para refrescar la pagina

def restar_producto(request, producto_id):

    carro=Carro(request)#creo objeto tipo carro

    producto=Producto.objects.get(id=producto_id)#obtengo el producto

    carro.restar_producto(producto=producto)

    return redirect('Tienda') #para refrescar la pagina

def limpiar_carro(request):

    carro=Carro(request)#creo objeto tipo carro

    carro.limpiar_carro()

    return redirect('Tienda') #para refrescar la pagina

def comprar_producto(request):  #función que envia mails, colocar mail correspondiente al que vas a utilizar (normalmente el que se coloco en el settings.py)


    userEmail=request.user.email
    userName=request.user.username
    
    for key, value in request.session.items():
        print('la llave es {} el valor es => {}'.format(key,value))
        
        if  key=="carro" :
            
            miEmail=EmailMessage('Mensaje de compra de mi app DJANGO', 'El Usuario con nombre {} con la dirección  {} quiere lo siguiente:\n\n {}'.format(userName,userEmail,value),
            '', ['TUMAIL@gmail.com'], reply_to=[userEmail])
            try:
                miEmail.send()
                return redirect('/tienda/?enviado')
            except:
                return redirect('/tienda/?noEnviado')

        
    
        
    

ProyectoWeb/tienda/views.py
from django.shortcuts import render

from .models import Producto

# Create your views here.

def tienda(request):

    productos=Producto.objects.all()

    return render(request, 'tienda/tienda.html', {'productos' : productos})

ProyectoWeb/tienda/templates/carro/widget.html
{% if user.username != "" %}
<table class='table table-bordered' style='color:white'>

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
            
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

                <tr class='text-center'>
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href='{% url "carro:agregar" value.producto_id %}' class='btn btn-sm btn-success'>+</a>
                        <a href='{% url "carro:restar" value.producto_id %}' class='btn btn-sm btn-success'>-</a><br>
                        {{value.precio}} $
                    </td>
                </tr>

            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class='alert alert-danger text-center'>Sin productos</div>
                    
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan='3'>
                Total: {{importe_total_carro}} $
            </td>
        </tr>
        <tr>
        
            {% if user.email != null %}
            
            {% if importe_total_carro != 0 %}
            <td colspan='2' class='text-center'><a href='{% url "carro:comprar" %}' class='btn btn-success'>Comprar</a></td>
            <td colspan='2' class='text-center'><a href='{% url "carro:limpiar" %}' class='btn btn-success'>Vaciar</a></td>

            {% endif %}
            

            
            {% endif %}
            
            
        </tr>
    </tfoot>

</table>
{% endif %}